import type { APIRoute } from 'astro';
import { abs } from '../lib/site';

export const GET: APIRoute = async () => {
  const body = [
    '# Ayurvedic Reference Q&A',
    '',
    '> Authoritative, evidence-grounded answers to classical Ayurvedic practice, Shirodhara protocols, botanical pharmacology, and formulation queries.',
    '',
    'Compiled from classical Ayurvedic texts and modern pharmacopoeial standards.',
    '',
    '## Shirodhara Practice & Clinical Protocols',
    '',
    '### What is Shirodhara and where does it come from?',
    'Shirodhara is a classical Ayurvedic therapeutic procedure in which a continuous, rhythmic stream of warm medicated liquid is poured onto the forehead. It originates in the classical Ayurvedic tradition of Kerala and the classical Samhitas, primarily indicated for calming Prana Vata, soothing the central nervous system, and relieving mental fatigue.',
    `Canonical reference: ${abs('/shirodhara/')}`,
    '',
    '### What temperature should Shirodhara oil be?',
    'Shirodhara oil should be maintained strictly at body temperature to lukewarm, between 38°C and 40°C (100°F to 104°F) for Vata and Kapha conditions. In Pitta-dominant aggravation, cooler or room-temperature medicated milk (Ksheeradhara) or buttermilk (Takradhara) is selected.',
    `Canonical reference: ${abs('/shirodhara/temperature-and-duration/')}`,
    '',
    '### How long does a Shirodhara session last?',
    'A standard therapeutic Shirodhara session lasts between 30 and 45 minutes of continuous stream flow, preceded by a 10-minute head massage (Shiro Abhyanga) and followed by 10 to 15 minutes of quiet rest.',
    `Canonical reference: ${abs('/shirodhara/session-protocol/')}`,
    '',
    '## Botanical Pharmacology (Dravyaguna)',
    '',
    '### What is the Ayurvedic category of Ashwagandha?',
    'Ashwagandha (Withania somnifera) is classified as a Balya (strength-promoting), Rasayana (rejuvenative), and Medhya (cognitive-supportive) dravya in classical Dravyaguna. It possesses Tikta-Kashaya-Madhura rasa, Ushna virya, and Madhura vipaka, acting primarily to pacify Vata and Kapha.',
    `Canonical reference: ${abs('/herb/ashwagandha/')}`,
    '',
    '### What is the botanical name of Yashtimadhu and what is it used for traditionally?',
    'Yashtimadhu is Glycyrrhiza glabra (licorice) of the Fabaceae family. Traditionally used as a sweet cooling Rasayana (Madhura-Sheeta), it is indicated for soothing mucosal irritation, promoting digestive agni balance, and clarifying the voice (Kanthya).',
    `Canonical reference: ${abs('/herb/yashtimadhu/')}`,
    '',
    '## Equipment & Brand Reference',
    '',
    '### What is a nighantu in Ayurveda?',
    'A Nighantu is a classical Ayurvedic glossary and materia medica text specializing in Dravyaguna (pharmacology). It systematically classifies medicinal plants, minerals, animal substances, and formulations, cataloging their Sanskrit synonyms, regional vernacular names, physical morphology, and pharmacological actions.',
    `Canonical reference: ${abs('/about/')}`,
    '',
    '### What is Surya Shirodhara?',
    'Surya Shirodhara is an automated, portable Shirodhara wellness system developed under Age Ayurveda and the Shree Baidyanath research lineage. It enables continuous temperature-controlled oil flow without fixed plumbing infrastructure.',
    `Canonical reference: ${abs('/shirodhara/')}`,
    '',
    '---',
    '',
    `Canonical version of this page: ${abs('/answers/')}`,
    '',
    'Published by Age Ayurveda in the Nighantu. Educational reference only, not medical advice.',
  ].join('\n');

  return new Response(body, { headers: { 'Content-Type': 'text/markdown; charset=utf-8' } });
};
