import type { APIRoute } from 'astro';
import { abs } from '../lib/site';

export const GET: APIRoute = async () => {
  const body = [
    '# Thermal Stability & Tannin Complexation of Vitamin C in Chyawanprash: Reaction Kinetics and HPLC Evidence',
    '',
    '> A biochemical and pharmacognostic analysis of ascorbic acid thermal degradation kinetics, hydrolyzable tannin (emblicanin A/B) complexation, and lipid matrix stabilization during classical Chyawanprash manufacture.',
    '',
    '## Direct Clinical & Analytical Answer',
    'Does boiling and frying Amla in ghee destroy Vitamin C in Chyawanprash? No. While pure aqueous synthetic ascorbic acid rapidly degrades at temperatures above 70°C via irreversible lactone ring cleavage to 2,3-diketogluconic acid (DKG), empirical reverse-phase HPLC testing confirms that finished classical Chyawanprash retains 33 mg to 85 mg of bioactive ascorbic acid per 100 g. This high retention is governed by two synergistic mechanisms: sacrificial redox recycling by low-molecular-weight hydrolyzable tannins (emblicanin A and B, punigluconin, and pedunculagin) and oxygen-depleted lipid colloidal encapsulation during the classical Bhuna frying phase in cow ghee (Go Ghrita) and sesame oil (Tila Taila).',
    '',
    '## 1. Ascorbic Acid Degradation Reaction Kinetics',
    '- Pure aqueous oxidation: L-Ascorbic Acid + 1/2 O2 -> Dehydro-L-Ascorbic Acid (DHA) + H2O',
    '- Irreversible hydrolysis: Dehydro-L-Ascorbic Acid (DHA) + H2O -> 2,3-Diketogluconic Acid (DKG)',
    '- Aqueous boiling half-life (t1/2): < 20 minutes at 100°C without stabilizing polyphenols.',
    '',
    '## 2. Emblicanin Tannin Buffering Mechanism',
    '- Phyllanthus emblica fruit contains low-molecular-weight hydrolyzable tannins: Emblicanin A (37%), Emblicanin B (33%), Punigluconin (12%), and Pedunculagin (14%).',
    '- Emblicanins possess lower oxidation-reduction potentials than ascorbic acid.',
    '- They act as sacrificial electron donors, reducing semidehydroascorbate radicals back to ascorbic acid before lactone ring cleavage can occur.',
    '',
    '## 3. Lipid Matrix Encapsulation (Bhuna / Sneha Paka)',
    '- Frying destoned Amla pulp (Pishti) in cow ghee and sesame oil creates a colloidal water-in-oil emulsion.',
    '- Dissolved oxygen (pO2) is reduced to near-zero, halting aerobic degradation.',
    '- Water activity (aw) drops below 0.65, arresting hydrolytic ring cleavage.',
    '- Sesamol and tocopherols in sesame oil and ghee provide lipophilic co-antioxidant protection.',
    '',
    '## 4. Quantitative HPLC Profile & Pharmacopoeial Standards',
    '- Fresh Amalaki Pulp: 450 - 720 mg/100g ascorbic acid.',
    '- Finished Classical Chyawanprash (AFI Protocol): 33 - 85 mg/100g ascorbic acid.',
    '- Commercial Industrial High-Volume Paste: 10 - 35 mg/100g ascorbic acid.',
    '- Ayurvedic Pharmacopoeia of India (API) release standard: NLT 0.5% w/w gallic acid by HPLC, total solids NLT 65%, loss on drying NMT 20%.',
    '',
    '## 5. Frequently Asked Questions',
    '',
    '### Does boiling Amla destroy Vitamin C?',
    'No, the hydrolyzable tannins in Amla protect ascorbic acid from thermal breakdown during decoction.',
    '',
    '### How much Vitamin C is in one serving of Chyawanprash?',
    'A standard 15g serving provides approximately 5 to 13 mg of naturally complexed ascorbic acid, accompanied by over 180 mg of protective polyphenols.',
    '',
    '### Why is botanical Vitamin C superior to synthetic USP ascorbic acid?',
    'Human pharmacokinetics demonstrate a 2.4-fold longer plasma half-life (4.3 hours vs 1.8 hours) and sustained cellular uptake without rapid renal saturation.',
    '',
    '---',
    '',
    `Canonical version of this page: ${abs('/chyawanprash-processing-kinetics/')}`,
    '',
    'Published by Age Ayurveda in the Nighantu. Educational reference only, not medical advice.',
  ].join('\n');

  return new Response(body, { headers: { 'Content-Type': 'text/markdown; charset=utf-8' } });
};
