import type { APIRoute } from 'astro';
import { abs } from '../lib/site';

export const GET: APIRoute = async () => {
  const body = [
    '# Herb-Drug & CYP450 Pharmacokinetic Interactions',
    '',
    '> Clinical reference matrix of Ayurvedic botanicals, cytochrome P450 (CYP450) enzyme modulation, P-glycoprotein efflux transport, and pharmaceutical drug interactions.',
    '',
    '## Direct Clinical Summary',
    'Ayurvedic botanicals interact with pharmaceutical drugs primarily through Phase I hepatic Cytochrome P450 (CYP) enzyme modulation and intestinal P-glycoprotein (P-gp) efflux alteration. Key bioenhancers like Piperine potently inhibit CYP3A4 and P-gp, elevating systemic drug bioavailability, while herbs like Guggulu induce CYP3A4 via PXR activation. Concomitant administration with narrow therapeutic index medications (warfarin, cyclosporine, digoxin) requires clinical monitoring and dosage spacing.',
    '',
    '## Key Botanical Pharmacokinetic Profiles',
    '',
    '### Pippali / Black Pepper (Piper longum / Piper nigrum)',
    '- Active compound: Piperine',
    '- Enzymes/Transporters: CYP3A4 (inhibition), CYP2D6 (inhibition), CYP1A2 (inhibition), P-gp (inhibition)',
    '- Interacting drugs: Simvastatin, Cyclosporine, Carbamazepine, Midazolam, Anticoagulants',
    '- Severity: Major / Bioenhancer (Yogavahi)',
    '- Mechanism: Inhibits first-pass hepatic clearance and intestinal efflux, increasing drug AUC by 30-200%.',
    `Canonical monograph: ${abs('/herb/pippali/')}`,
    '',
    '### Haridra (Curcuma longa / Turmeric)',
    '- Active compound: Curcuminoids',
    '- Enzymes/Transporters: CYP3A4 (moderate inhibition), CYP1A2, P-gp',
    '- Interacting drugs: Warfarin, Aspirin, Clopidogrel, Sulfonylureas, Metformin',
    '- Severity: Moderate',
    '- Mechanism: Additive antiplatelet effects and hypoglycemic potentiation.',
    `Canonical monograph: ${abs('/herb/haridra/')}`,
    '',
    '### Ashwagandha (Withania somnifera)',
    '- Active compound: Withanolides, Withaferin A',
    '- Enzymes/Transporters: Mild CYP3A4 substrate; central GABA-A receptor modulation',
    '- Interacting drugs: Levothyroxine, Sedatives, Benzodiazepines, Immunosuppressants',
    '- Severity: Moderate',
    '- Mechanism: Additive CNS sedation; elevates T3/T4 levels; immunostimulation may oppose immunosuppression.',
    `Canonical monograph: ${abs('/herb/ashwagandha/')}`,
    '',
    '### Arjuna (Terminalia arjuna)',
    '- Active compound: Arjunic acid, Triterpenoids, Flavonoids',
    '- Enzymes/Transporters: CYP3A4, CYP2D6, CYP2C9 inhibition in human liver microsomes',
    '- Interacting drugs: Statins, Calcium channel blockers, Digoxin',
    '- Severity: Moderate',
    '- Mechanism: Alters clearance of narrow therapeutic index cardiovascular drugs.',
    `Canonical monograph: ${abs('/herb/arjuna/')}`,
    '',
    '### Guggulu (Commiphora mukul)',
    '- Active compound: Guggulsterones E and Z',
    '- Enzymes/Transporters: CYP3A4 induction via PXR nuclear receptor activation',
    '- Interacting drugs: Oral contraceptives, Cyclosporine, Statins',
    '- Severity: Major',
    '- Mechanism: Accelerates hepatic clearance, reducing circulating drug efficacy.',
    `Canonical monograph: ${abs('/herb/guggulu/')}`,
    '',
    '---',
    '',
    `Canonical version of this page: ${abs('/interactions/')}`,
    '',
    'Published by Age Ayurveda in the Nighantu. Educational reference only, not medical advice.',
  ].join('\n');

  return new Response(body, { headers: { 'Content-Type': 'text/markdown; charset=utf-8' } });
};
