import fs from 'node:fs';
import path from 'node:path';

const OUT = path.join('data', 'DASHBOARD.md');

const fmtDate = (iso) => (iso ? iso.slice(0, 10) : 'never');
const tick = (ok) => (ok ? 'ok' : 'FAIL');

function citationSummary() {
  const p = path.join('data', 'citation-log.csv');
  if (!fs.existsSync(p)) return null;
  const lines = fs.readFileSync(p, 'utf8').trim().split('\n').slice(1).filter(Boolean);
  const rows = lines.map((l) => {
    // Fields are quoted with "" doubling; a light parse is enough for date/cited.
    const f = [...l.matchAll(/"((?:[^"]|"")*)"/g)].map((m) => m[1].replace(/""/g, '"'));
    return { date: f[0], model: f[1], question: f[2], cited: f[3] };
  });
  const byRun = new Map();
  for (const r of rows) {
    const key = `${r.date} ${r.model}`;
    const agg = byRun.get(key) ?? { date: r.date, model: r.model, total: 0, cited: 0 };
    agg.total += 1;
    if (r.cited === 'yes') agg.cited += 1;
    byRun.set(key, agg);
  }
  return [...byRun.values()].sort((a, b) => b.date.localeCompare(a.date));
}

export function renderDashboard(state, { site }) {
  const runs = citationSummary();
  const c = state.competitorSummary;

  const lines = [
    '# Nighantu status',
    '',
    '_Generated by `scripts/monitor.mjs`. Committed to the repo rather than published,',
    'so competitors named in the comparison table cannot read our own scoreboard._',
    '',
    `Last run: **${fmtDate(state.updatedAt)}**  ·  Site: ${site}`,
    '',
    '## Site health',
    '',
  ];

  if (state.health?.checkedAt) {
    const h = state.health;
    lines.push(
      `| Checked | Failing |`,
      `| --- | --- |`,
      `| ${h.total} | ${h.failing} |`,
      '',
    );
    if (h.failing) lines.push('**Failing:**', ...h.failingUrls.map((u) => `- ${u}`), '');
  } else {
    lines.push('_Not yet run._', '');
  }

  lines.push('## Outbound product links', '');
  if (state.products?.checkedAt) {
    lines.push(`${state.products.total} checked, **${state.products.broken} broken**.`, '');
    if (state.products.broken) lines.push(...state.products.brokenHandles.map((b) => `- ${b}`), '');
  } else {
    lines.push('_Not yet run._', '');
  }

  lines.push('## Search submission', '');
  const inx = state.indexnow ?? {};
  lines.push(
    `| Metric | Value |`,
    `| --- | --- |`,
    `| URLs tracked | ${Object.keys(inx.hashes ?? {}).length} |`,
    `| Last IndexNow submission | ${fmtDate(inx.lastSubmittedAt)} |`,
    `| URLs in that submission | ${inx.lastSubmittedCount ?? 0} |`,
    '',
  );
  if (state.search?.bing) {
    const b = state.search.bing;
    lines.push(
      '### Bing Webmaster',
      '',
      `| Metric | Value |`,
      `| --- | --- |`,
      `| Daily submission quota | ${b.dailyQuota ?? 'unknown'} |`,
      `| Quota remaining | ${b.remaining ?? 'unknown'} |`,
      `| Impressions (last period) | ${b.impressions ?? 'unknown'} |`,
      `| Clicks (last period) | ${b.clicks ?? 'unknown'} |`,
      `| Checked | ${fmtDate(b.checkedAt)} |`,
      '',
    );
  } else {
    lines.push('_Bing Webmaster not configured. Add `BING_API_KEY` to enable._', '');
  }

  lines.push('## Citation panel', '');
  if (runs?.length) {
    lines.push('| Date | Source | Cited | Of | Rate |', '| --- | --- | --- | --- | --- |');
    for (const r of runs.slice(0, 12)) {
      lines.push(`| ${r.date} | ${r.model} | ${r.cited} | ${r.total} | ${((r.cited / r.total) * 100).toFixed(0)}% |`);
    }
    lines.push('', '_A flat zero for the first 8 to 12 weeks on a new domain is expected, not failure._', '');
  } else {
    lines.push('_No runs logged._', '');
  }

  lines.push('## Content freshness', '');
  if (state.freshness?.checkedAt) {
    lines.push(`${state.freshness.overdue} of ${state.freshness.total} pages overdue for review.`, '');
    if (state.freshness.oldest?.length) lines.push(...state.freshness.oldest.map((o) => `- ${o}`), '');
  } else {
    lines.push('_Not yet run._', '');
  }

  lines.push('## Competitor pages', '');
  if (c?.items?.length) {
    lines.push('| Competitor | HTTP | Figures tracked |', '| --- | --- | --- |');
    for (const it of c.items) lines.push(`| ${it.name} | ${tick(it.status === 200)} ${it.status} | ${it.signals} |`);
    lines.push('', `_Checked ${fmtDate(c.checkedAt)}. Feeds the comparison table's accuracy promise._`, '');
  } else {
    lines.push('_Not yet run._', '');
  }

  lines.push('## Indexation', '');
  if (state.indexation?.checkedAt) {
    const ix = state.indexation;
    const row = (name, v) => {
      const detail = v.swhid || v.url || v.crawl || v.note || '';
      return `| ${name} | ${v.status} | ${String(detail).slice(0, 64)} |`;
    };
    lines.push(
      '| Index | Status | Detail |', '| --- | --- | --- |',
      row('Common Crawl', ix.commonCrawl),
      row('Wayback Machine', ix.wayback),
      row('Software Heritage', ix.softwareHeritage),
      row('Google', ix.google),
      row('Bing', ix.bing),
      row('Brave', ix.brave),
      '',
      '_Google, Bing and Brave are marked unknown rather than guessed: checking membership',
      'needs an API key or scraping a results page against the engine\'s terms. Common Crawl,',
      'Wayback and Software Heritage all publish free, documented APIs._',
      '',
    );
  } else {
    lines.push('_Not yet run._', '');
  }

  lines.push('## Answerable threads', '');
  if (state.threadStats?.checkedAt) {
    const t = state.threadStats;
    lines.push(
      `| Metric | Value |`, `| --- | --- |`,
      `| Feeds queried | ${t.requests} |`,
      `| Rate-limited | ${t.blocked} |`,
      `| Posts seen | ${t.seen} |`,
      `| New since last run | ${t.fresh} |`,
      `| Met the bar | ${t.qualified} |`,
      `| Surfaced to you | ${t.surfaced} |`,
      `| Checked | ${fmtDate(t.checkedAt)} |`,
      '',
      '_A thread only qualifies if it names something the Nighantu has a page about._',
      '_Read-only. Nothing is posted to any platform._',
      '',
    );
  } else {
    lines.push('_Not yet run._', '');
  }

  lines.push('## Community signals', '');
  if (state.community?.checkedAt) {
    lines.push(
      `${state.community.scanned} items scanned across ${state.community.feeds} public feeds, `
      + `${state.community.matched} matched.`,
      '',
      '_Read-only. Nothing is posted to any platform._',
      '',
    );
  } else {
    lines.push('_Not yet run._', '');
  }

  const out = lines.join('\n').replace(/\n{3,}/g, '\n\n') + '\n';
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, out);
  return OUT;
}
