/**
 * The retracted-paper blocklist.
 *
 * A citation to a retracted paper is worse than a citation to a paper that does not
 * exist. The fabricated one fails the moment anyone follows it; the retracted one
 * resolves, looks entirely normal, and carries the authority of a real journal record
 * while the finding it reports has been withdrawn.
 *
 * 14 were found across 2,906 cited papers on the first sweep, all of them invisible
 * until PubMed was asked directly. They are excluded by PMID rather than by any
 * heuristic, because the only reliable signal is PubMed's own publication type, and the
 * list is regenerated by scripts/check-retractions.mjs rather than maintained by hand.
 *
 * This must be re-run on a schedule, not once. A paper cited today can be retracted next
 * year, and nothing about our copy of the citation would change when it is.
 */
import fs from 'node:fs';
import path from 'node:path';

const FILE = path.join('data', 'retractions.json');
let cache = null;

export function loadRetracted() {
  if (cache) return cache;
  cache = new Set();
  if (!fs.existsSync(FILE)) return cache;
  try {
    const d = JSON.parse(fs.readFileSync(FILE, 'utf8'));
    for (const f of d.flagged ?? []) cache.add(String(f.pmid));
  } catch (e) {
    // A missing or broken list must not silently disable the filter, because the
    // failure mode is publishing retracted science.
    console.error(`retraction list unreadable (${e.message}); treating as EMPTY, re-run scripts/check-retractions.mjs`);
  }
  return cache;
}

export const isRetracted = (pmid) => loadRetracted().has(String(pmid));

/** Strip retracted papers from a citation list, reporting what went. */
export function dropRetracted(citations = []) {
  const kept = [];
  const dropped = [];
  for (const c of citations) (isRetracted(c.pmid) ? dropped : kept).push(c);
  return { kept, dropped };
}
