/**
 * The do-not-cite blocklist.
 *
 * NAMED FOR WHAT IT IS, after it stopped being only about retractions. It now also carries
 * correction notices: a "Corrigendum: <original title>" record that a citation harvester matched
 * instead of the article it corrects. Those are not retracted, and three of them were sitting in
 * the corpus as tier D papers. Calling the test `isRetracted` would have made it return true for a
 * perfectly sound journal record, which is a falsehood this project would eventually publish in a
 * log line or a comment. `kindOf` says which reason applies.
 *
 * A citation to a retracted paper is worse than a citation to a paper that does not
 * exist. The fabricated one fails the moment anyone follows it; the retracted one
 * resolves, looks entirely normal, and carries the authority of a real journal record
 * while the finding it reports has been withdrawn.
 *
 * 14 were found across 2,906 cited papers on the first sweep, all of them invisible
 * until PubMed was asked directly. They are excluded by PMID rather than by any
 * heuristic, because the only reliable signal is PubMed's own publication type, and the
 * list is regenerated by scripts/check-retractions.mjs rather than maintained by hand.
 *
 * This must be re-run on a schedule, not once. A paper cited today can be retracted next
 * year, and nothing about our copy of the citation would change when it is.
 */
import fs from 'node:fs';
import path from 'node:path';

const FILE = path.join('data', 'retractions.json');
let cache = null;
const kinds = new Map();

export function loadBlocklist() {
  if (cache) return cache;
  cache = new Set();
  if (!fs.existsSync(FILE)) return cache;
  try {
    const d = JSON.parse(fs.readFileSync(FILE, 'utf8'));
    for (const f of d.flagged ?? []) {
      cache.add(String(f.pmid));
      kinds.set(String(f.pmid), f.kind ?? 'unknown');
    }
  } catch (e) {
    // A missing or broken list must not silently disable the filter, because the
    // failure mode is publishing retracted science.
    console.error(`retraction list unreadable (${e.message}); treating as EMPTY, re-run scripts/check-retractions.mjs`);
  }
  return cache;
}

export const isBlocked = (pmid) => loadBlocklist().has(String(pmid));

/** Why a PMID is blocked: 'retracted-publication', 'retraction-notice' or 'erratum-notice'. */
export function kindOf(pmid) {
  loadBlocklist();
  return kinds.get(String(pmid)) ?? null;
}

/** Strip blocked papers from a citation list, reporting what went and why. */
export function dropBlocked(citations = []) {
  const kept = [];
  const dropped = [];
  for (const c of citations) (isBlocked(c.pmid) ? dropped : kept).push(c);
  return { kept, dropped: dropped.map((c) => ({ ...c, blockedBecause: kindOf(c.pmid) })) };
}
